server:
  port: 8002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: *****
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      stat-view-servlet:
        login-password: *****
        login-username: *****
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    password: nkmoiopxrermbigj
    username: afblog@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  type-aliases-package: com.af.blog.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true   # 分页合理化参数，默认为false。true 时：pageNum <=0 会查第一页， 大于总页数时，会查最后一页
  support-methods-arguments: true  # 支持通过Mapper接口参数来传递分页参数
